### ISSUE TITLE
Bug: jumping up will always make you face right

### ISSUE THREAD

**Issue by AdamLearns** [AdamLearns/JumpRoyale#21]
Reported by smu.

If you're facing left when you type `u`, you should still be facing left after the jump.

**Comment by DarkStoorM** [comment]
I assume this flip assignment is at fault here, should probably rely on storing the last facing direction:

https://github.com/AdamLearns/JumpRoyale/blob/3c9af498d40eba04843004fd13987d59d7ab7b94/src/Jumper.cs#L128-L133

Also works with `l` btw

**Comment by AdamLearns** [comment]
Fixed by #38.
