### ISSUE TITLE
QoL: PR size

### ISSUE THREAD

**Issue by DarkStoorM** [AdamLearns/JumpRoyale#26]
Not really needed, but sometimes it's nice to have an immediate feedback on what's the approximate size of new PRs. It will add labels to the PRs based on the amount of lines changes.

https://github.com/apps/pull-request-size

PR size in action in another game project ([osu!](https://github.com/ppy/osu/pulls)):
![img](https://github.com/AdamLearns/JumpRoyale/assets/7021295/476aed61-c568-4895-b731-7dabdc7bd8cc)

**Comment by AdamLearns** [comment]
I don't think I'm going to move forward with this. I'll probably end up looking at all of the PRs anyway, and I can just look at the number of files changed to eyeball the size of the PR. Plus, I can look at the upper right of the PR page: 
<img width="179" alt="image" src="https://github.com/AdamLearns/JumpRoyale/assets/60950402/db9394d5-44ef-4d03-b64f-caa106ffa1f5">
