### ISSUE TITLE
Automatic game restart

### ISSUE THREAD

**Issue by DarkStoorM** [AdamLearns/JumpRoyale#27]
During the result screen, there could be a 30s countdown timer, restarting the game automatically after that period.

**Stream related**: lunch breaks are long, you sometimes might want to leave the stream running so the viewers could play the game, but it depends if you always raid people during the lunch breaks.

Assuming the lunch breaks are around 40 minutes:

- a single game session is 180 seconds, assuming 210 if the 30 seconds delay is also added to the result screen
  - 30s to join
  - 150s to play
  - 30s in the results
- there can potentially be 11 sessions at most (40 minutes), ~8 in 30 minutes

**Comment by AdamLearns** [comment]
I think I'd rather have a dedicated game or some other segment of content during my lunch breaks (see [this task](https://github.com/users/AdamLearns/projects/4/views/1?pane=issue&itemId=48241856)). I think that Jump Royale would feel somewhat stale after ~5 games in a row, and the playerbase would keep dwindling. It would also further increase the skill gap between new/old players given that it's a competitive game.
