### ISSUE TITLE
Limit the active platforms to only be within camera view

### ISSUE THREAD

**Issue by HoppenR** [AdamLearns/JumpRoyale#33]
The arena platforms and blocks should only spawn in once they are right above the camera view, and similarly de-spawn once they go below the camera view. This prevents players from being able to jump massively ahead above the visible arena, and prevents comebacks from players who fell off the screen.

This helps check off the following `Design`-points in Adam's notes:
- The world is procedurally generated. This isn't even a requirement at first; it could be static to start with or be built out of predetermined chunks that get pieced together.
- Only so much of the arena can be viewed at a time. Players who are off-screen for any reason are eliminated.

Alternatively we can also keep platforms and/or blocks for a bit below the camera to promote *a little bit* of comeback.

I am willing to attempt this if there is enough interest in this.

**Comment by smu4242** [comment]
My initial thought was that platforms should live even shorter - meaning they spawn not right above the camera view, but just within the camera view. But I also like this idea :D

**Comment by DarkStoorM** [comment]
Yeah, for now, it sometimes feels like cheating when you are at the top and the game speeds up. If you get lucky enough to get 3 platforms straight up, you force the camera to scroll faster at you, potentially eliminating players at the bottom of the screen.

With the limitation of just a couple units above the viewport, the forced scroll won't be that dangerous. But who knows, maybe that's the *competitive* part of this game 😉 

Regarding the off-screen elimination, I think there could be some sort of *grey-area*, e.g. as tall as the maximum power jump height, then anything below that is just deleted - rough measurement: currently almost as tall as the lobby "cage".

**Comment by Caleb-T-Owens** [comment]
It's just part of the strategy of the game. If you're preempting moves and it looks like you're going to head off-screen, going `jump 0` a few times is just good practice
