### ISSUE TITLE
Prevent reviving in the last X seconds

### ISSUE THREAD

**Issue by AdamLearns** [AdamLearns/JumpRoyale#48]
(note: this was part of #14, but I wanted to separate the issues out)

- Prevent reviving using channel points if X seconds remain in the game. X is open for discussion, but I think a good starting point is 30.
- After this is done, make sure to change the description of my channel-point reward to mention the thing about X.

**Comment by DarkStoorM** [comment]
I think this could be handled through Twitch API, automatically updating custom reward when there's x seconds left. There is an httpClient included in recent PR (TwitchClient), so we could have a simple `RewardsManager` that Arena could communicate with, like:

```csharp
                \/-- some meaningful name here
if (TimeLeft <= 30)
{
  // \/ this, OR store the constructor's TwitchChatClient to call the exposed methods directly on the client
  rewardsManager.DisableReviving();
  // Re-enabling could occur either on game start or right after the game ended
}
```

Should probably convert TwitchChatClient into singleton instead 🤔 

https://dev.twitch.tv/docs/api/reference/#update-custom-reward
This also should probably be better than keeping the rewards open and refunding if there is not enough time left
