### ISSUE TITLE
Make names of winners fit on the end screen

### ISSUE THREAD

**Issue by AdamLearns** [AdamLearns/JumpRoyale#49]
Now that player names are big, the winners' names go off the top of the screen:

![Image](https://github.com/AdamLearns/JumpRoyale/assets/60950402/8409253c-1981-4187-a15e-94e099017802)

Ideas:

- Could just shrink the names of the winners a bit.
- Could lower the podiums a bit.

**Comment by smu4242** [comment]
that's my bad. I can take a look at this in a few days.
