### ISSUE TITLE
Bug: you can get stuck against a block and a platform

### ISSUE THREAD

**Issue by AdamLearns** [AdamLearns/JumpRoyale#55]
See [this clip](https://clips.twitch.tv/FairLuckySeahorseCoolCat-SaUiv2la6HqWmINv) for an example (see `fatooty_gg` at the top about halfway through the clip).

Note that I haven't looked into what's causing this, so I don't know how best to fix this.

**Comment by smu4242** [comment]
Looks like this happens when a player is at the same location where a block spawns.

Idea: We could add a line of blocks at the top, like we have at the border, but this one would move up with the scroll.
